name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Build images
        run: |
          docker build --pull -t kooldev/toolkit:terraform-aws terraform-aws
          docker build -t kooldev/toolkit:full full

      - name: Test docker images
        run: |
          docker run -t --rm kooldev/toolkit:terraform-aws terraform --version
          docker run -t --rm kooldev/toolkit:terraform-aws aws --version

          docker run -t --rm kooldev/toolkit:full terraform --version
          docker run -t --rm kooldev/toolkit:full aws --version
          docker run -t --rm kooldev/toolkit:full kubectl --help
          docker run -t --rm kooldev/toolkit:full docker --version
          docker run -t --rm kooldev/toolkit:full docker-compose --version
          docker run -t --rm kooldev/toolkit:full doctl version
          docker run -t --rm kooldev/toolkit:full helm version

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push to Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'kool-dev/docker-toolkit'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push kooldev/toolkit:terraform-aws
          docker push kooldev/toolkit:full
